// authentication types
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LOGIN_START = "LOGIN_START"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_STOP = "LOGIN_STOP"

export const SET_USER_DATA = "SET_USER_DATA"
export const GET_USER_DATA_STOP = "GET_USER_DATA_STOP"
export const GET_USER_DATA_START = "GET_USER_DATA_START"
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR"
export const LOG_USER_OUT = "LOG_USER_OUT"

export const ADD_START = "ADD_START"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const ADD_ERROR = "ADD_ERROR"
export const ADD_STOP = "ADD_STOP"

export const SIGNUP_LOADING = "SIGNUP_LOADING"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_STOP = "SIGNUP3_STOP"

export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_ERROR = "LOGOUT_ERROR"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_STOP = "LOGOUT_STOP"

// authentication types ends here
// dashboard types starts here
export const GET_DASHBOARD_START = "GET_DASHBOARD_START"
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR"
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS"
export const GET_DASHBOARD_END = "GET_DASHBOARD_END"

// dashboard types starts here
export const GET_MONITORED_KEYWORDS_START = "GET_MONITORED_DASHBOARD_START"
export const GET_MONITORED_KEYWORDS_ERROR = "GET_MONITORED_DASHBOARD_ERROR"
export const GET_MONITORED_KEYWORDS_SUCCESS = "GET_MONITORED_DASHBOARD_SUCCESS"
export const GET_MONITORED_KEYWORDS_END = "GET_MONITORED_DASHBOARD_END"

export const GET_WEBSITE_MONITORING_DATA_START =
  "GET_WEBSITE_MONITORING_DATA_START"
export const GET_WEBSITE_MONITORING_DATA_ERROR =
  "GET_WEBSITE_MONITORING_DATA_ERROR"
export const GET_WEBSITE_MONITORING_DATA_SUCCESS =
  "GET_WEBSITE_MONITORING_DATA_SUCCESS"
export const GET_WEBSITE_MONITORING_DATA_END = "GET_WEBSITE_MONITORING_DATA_END"
// website monitoring ends here

//twisted DNS Data
export const GET_TWISTED_DNS_START = "GET_TWISTED_DNS_START"
export const GET_TWISTED_DNS_ERROR = "GET_TWISTED_DNS_ERROR"
export const GET_TWISTED_DNS_SUCCESS = "GET_TWISTED_DNS_SUCCESS"
export const GET_TWISTED_DNS_END = "GET_TWISTED_DNS_END"
// twisted DNS Data ends here

//send takedown email
export const SEND_TAKEDOWN_MAIL_START = "SEND_TAKEDOWN_MAIL_START"
export const SEND_TAKEDOWN_MAIL_ERROR = "SEND_TAKEDOWN_MAIL_ERROR"
export const SEND_TAKEDOWN_MAIL_SUCCESS = "SEND_TAKEDOWN_MAIL_SUCCESS"
export const SEND_TAKEDOWN_MAIL_END = "SEND_TAKEDOWN_MAIL_END"

//send app takedown email
export const SEND_APP_TAKEDOWN_MAIL_START = "SEND_APP_TAKEDOWN_MAIL_START"
export const SEND_APP_TAKEDOWN_MAIL_ERROR = "SEND_APP_TAKEDOWN_MAIL_ERROR"
export const SEND_APP_TAKEDOWN_MAIL_SUCCESS = "SEND_APP_TAKEDOWN_MAIL_SUCCESS"
export const SEND_APP_TAKEDOWN_MAIL_END = "SEND_APP_TAKEDOWN_MAIL_END"

//fetch takedown email
export const FETCH_TAKEDOWN_MAIL_START = "FETCH_TAKEDOWN_MAIL_START"
export const FETCH_TAKEDOWN_MAIL_ERROR = "FETCH_TAKEDOWN_MAIL_ERROR"
export const FETCH_TAKEDOWN_MAIL_SUCCESS = "FETCH_TAKEDOWN_MAIL_SUCCESS"
export const FETCH_TAKEDOWN_MAIL_END = "FETCH_TAKEDOWN_MAIL_END"

//update takedown email
export const UPDATE_TAKEDOWN_MAIL_START = "UPDATE_TAKEDOWN_MAIL_START"
export const UPDATE_TAKEDOWN_MAIL_ERROR = "UPDATE_TAKEDOWN_MAIL_ERROR"
export const UPDATE_TAKEDOWN_MAIL_SUCCESS = "UPDATE_TAKEDOWN_MAIL_SUCCESS"
export const UPDATE_TAKEDOWN_MAIL_END = "UPDATE_TAKEDOWN_MAIL_END"

//update takedown status
export const UPDATE_TAKEDOWN_STATUS_START = "UPDATE_TAKEDOWN_STATUS_START"
export const UPDATE_TAKEDOWN_STATUS_ERROR = "UPDATE_TAKEDOWN_STATUS_ERROR"
export const UPDATE_TAKEDOWN_STATUS_SUCCESS = "UPDATE_TAKEDOWN_STATUS_SUCCESS"
export const UPDATE_TAKEDOWN_STATUS_END = "UPDATE_TAKEDOWN_STATUS_END"

//fetch chart data
export const FETCH_TAKEDOWN_CHARTDATA_END = "FETCH_TAKEDOWN_CHARTDATA_END"
export const FETCH_TAKEDOWN_CHARTDATA_ERROR = "FETCH_TAKEDOWN_CHARTDATA_ERROR"
export const FETCH_TAKEDOWN_CHARTDATA_START = "FETCH_TAKEDOWN_CHARTDATA_START"
export const FETCH_TAKEDOWN_CHARTDATA_SUCCESS =
  "FETCH_TAKEDOWN_CHARTDATA_SUCCESS"

//update change password
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START"
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_END = "CHANGE_PASSWORD_END"

export const ADD_KEYWORDS_START = "ADD_KEYWORDS_START"
export const ADD_KEYWORDS_ERROR = "ADD_KEYWORDS_ERROR"
export const ADD_KEYWORDS_SUCCESS = "ADD_KEYWORDS_ERROR"
export const ADD_KEYWORDS_END = "ADD_KEYWORDS_END"

export const ADD_DOMAINS_START = "ADD_DOMAINS_START"
export const ADD_DOMAINS_ERROR = "ADD_DOMAINS_ERROR"
export const ADD_DOMAINS_SUCCESS = "ADD_DOMAINS_SUCCESS"
export const ADD_DOMAINS_END = "ADD_DOMAINS_END"

//GET PDF
export const GET_DASHBOARD_PDF_START = "GET_DASHBOARD_PDF_START"
export const GET_DASHBOARD_PDF_SUCCESS = "GET_DASHBOARD_PDF_SUCCESS"
export const GET_DASHBOARD_PDF_ERROR = "GET_DASHBOARD_PDF_ERROR"
export const GET_DASHBOARD_PDF_END = "GET_DASHBOARD_PDF_END"

//GET RAISED PDF
export const GET_RAISED_PDF_START = "GET_RAISED_PDF_START"
export const GET_RAISED_PDF_SUCCESS = "GET_RAISED_PDF_SUCCESS"
export const GET_RAISED_PDF_ERROR = "GET_RAISED_PDF_ERROR"
export const GET_RAISED_PDF_END = "GET_RAISED_PDF_END"

//GET DARK WEB PDF
export const GET_DARK_WEB_PDF_START = "GET_DARK_WEB_PDF_START"
export const GET_DARK_WEB_PDF_SUCCESS = "GET_DARK_WEB_PDF_SUCCESS"
export const GET_DARK_WEB_PDF_ERROR = "GET_DARK_WEB_PDF_ERROR"
export const GET_DARK_WEB_PDF_END = "GET_DARK_WEB_PDF_END"

//GET TWISTED DNS PDF
export const GET_TWISTED_DNS_PDF_START = "GET_TWISTED_DNS_PDF_START"
export const GET_TWISTED_DNS_PDF_SUCCESS = "GET_TWISTED_DNS_PDF_SUCCESS"
export const GET_TWISTED_DNS_PDF_ERROR = "GET_TWISTED_DNS_PDF_ERROR"
export const GET_TWISTED_DNS_PDF_END = "GET_TWISTED_DNS_PDF_END"

//SEND TWISTED DNS PDF
export const GET_TWISTED_DNS_PDF_SEND_START = "GET_TWISTED_DNS_PDF_START"
export const GET_TWISTED_DNS_PDF_SEND_SUCCESS = "GET_TWISTED_DNS_PDF_SUCCESS"
export const GET_TWISTED_DNS_PDF_SEND_ERROR = "GET_TWISTED_DNS_PDF_ERROR"
export const GET_TWISTED_DNS_PDF_SEND_END = "GET_TWISTED_DNS_PDF_END"

//GET WEBSITE MONITORING PDF
export const GET_WEBSITE_MONITORING_PDF_START =
  "GET_WEBSITE_MONITORING_PDF_START"
export const GET_WEBSITE_MONITORING_PDF_SUCCESS =
  "GET_WEBSITE_MONITORING_PDF_SUCCESS"
export const GET_WEBSITE_MONITORING_PDF_ERROR =
  "GET_WEBSITE_MONITORING_PDF_ERROR"
export const GET_WEBSITE_MONITORING_PDF_END = "GET_WEBSITE_MONITORING_PDF_END"

//SEND PDF
export const GET_DASHBOARD_PDF_SEND_START = "GET_DASHBOARD_PDF_START"
export const GET_DASHBOARD_PDF_SEND_SUCCESS = "GET_DASHBOARD_PDF_SUCCESS"
export const GET_DASHBOARD_PDF_SEND_ERROR = "GET_DASHBOARD_PDF_ERROR"
export const GET_DASHBOARD_PDF_SEND_END = "GET_DASHBOARD_PDF_END"

export const GET_SOCIAL_MEDIA_PERCENTAGE_START =
  "GET_SOCIAL_MEDIA_PERCENTAGE_START"
export const GET_SOCIAL_MEDIA_PERCENTAGE_ERROR =
  "GET_SOCIAL_MEDIA_PERCENTAGE_ERROR"
export const GET_SOCIAL_MEDIA_PERCENTAGE_SUCCESS =
  "GET_SOCIAL_MEDIA_PERCENTAGE_SUCCESS"
export const GET_SOCIAL_MEDIA_PERCENTAGE_END = "GET_SOCIAL_MEDIA_PERCENTAGE_END"

//latest keyword types starts here
export const GET_LATEST_KEYWORDS_START = "GET_LATEST_KEYWORDS_START"
export const GET_LATEST_KEYWORDS_ERROR = "GET_LATEST_KEYWORDS_ERROR"
export const GET_LATEST_KEYWORDS_SUCCESS = "GET_LATEST_KEYWORDS_SUCCESS"
export const GET_LATEST_KEYWORDS_END = "GGET_LATEST_KEYWORDS_END"
//latest keyword types end her

//OTP TYPES starts here
export const SEND_OTP_START = "SEND_OTP_START"
export const SEND_OTP_ERROR = "SEND_OTP_ERROR"
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS"
export const SEND_OTP_END = "SEND_OTP_END"

//VERIFY OTP TYPES starts here
export const VERIFY_OTP_START = "VERIFY_OTP_START"
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_END = "VERIFY_OTP_END"

//CHANGE PASSWORD TYPES starts here
export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START"
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_END = "UPDATE_PASSWORD_END"

// FETCH TOP GOOGLE SEARCH
export const FETCH_TOP_GOOGLE_SEARCH_START = "FETCH_TOP_GOOGLE_SEARCH_START"
export const FETCH_TOP_GOOGLE_SEARCH_ERROR = "FETCH_TOP_GOOGLE_SEARCH_ERROR"
export const FETCH_TOP_GOOGLE_SEARCH_SUCCESS = "FETCH_TOP_GOOGLE_SEARCH_SUCCESS"
export const FETCH_TOP_GOOGLE_SEARCH_END = "FETCH_TOP_GOOGLE_SEARCH_END"

// DELETE GOOGLE SEARCH LINK
export const DELETE_GOOGLE_SEARCH_LINK_START = "DELETE_GOOGLE_SEARCH_LINK_START"
export const DELETE_GOOGLE_SEARCH_LINK_ERROR = "DELETE_GOOGLE_SEARCH_LINK_ERROR"
export const DELETE_GOOGLE_SEARCH_LINK_SUCCESS =
  "DELETE_GOOGLE_SEARCH_LINK_SUCCESS"
export const DELETE_GOOGLE_SEARCH_LINK_END = "DELETE_GOOGLE_SEARCH_LINK_END"

//FETCH NOTIFICATIONS SETTINGS
export const FETCH_NOTIFICATIONS_SETTING_START =
  "FETCH_NOTIFICATIONS_SETTING_START"
export const FETCH_NOTIFICATIONS_SETTING_ERROR =
  "FETCH_NOTIFICATIONS_SETTING_ERROR"
export const FETCH_NOTIFICATIONS_SETTING_SUCCESS =
  "FETCH_NOTIFICATIONS_SETTING_SUCCESS"
export const FETCH_NOTIFICATIONS_SETTING_END = "FETCH_NOTIFICATIONS_SETTING_END"

// UPDATE NOTIFICATIONS SETTINGS
export const UPDATE_NOTIFICATIONS_SETTING_START =
  "UPDATE_NOTIFICATIONS_SETTING_START"
export const UPDATE_NOTIFICATIONS_SETTING_ERROR =
  "UPDATE_NOTIFICATIONS_SETTING_ERROR"
export const UPDATE_NOTIFICATIONS_SETTING_SUCCESS =
  "UPDATE_NOTIFICATIONS_SETTING_SUCCESS"
export const UPDATE_NOTIFICATIONS_SETTING_END =
  "UPDATE_NOTIFICATIONS_SETTING_END"

//CLEAR AND LOG OUT
export const LOG_OUT_AND_CLEAR = "LOG_OUT_AND_CLEAR"
