let BASE_URL = "http://150.230.48.46:8888/"
if (process.env.NODE_ENV !== "production") {
  BASE_URL = "http://150.230.48.46:8888/"
}
export const LOGIN = BASE_URL + "api/users/login/"
export const REGISTER = BASE_URL + "api/users/register/"
export const DASHBOARD = "api/dashboard/"
export const MONITOR_DOMAIN = (domain = "") =>
  `https://opensquat1.p.rapidapi.com/${domain}`
export const LOGO_DETECTON =
  "https://brand-recognition.p.rapidapi.com/v1/results"
export const VERSION = "https://brand-recognition.p.rapidapi.com/v1/version"
export const EMOTION =
  "https://ekman-emotion-analysis.p.rapidapi.com/ekman-emotion"
export const SCAM = (url = "") =>
  `https://exerra-phishing-check.p.rapidapi.com?url=${url}`
export const RAPID_GET_ALL = "https://exerra-phishing-check.p.rapidapi.com/all"
export const RAPID_GET_STATS =
  "https://exerra-phishing-check.p.rapidapi.com/stats"
export const SOCIAL_SCANNER =
  "https://social-scanner.p.rapidapi.com/social-scan/"
export const JOB_SEARCHES = "api/job-searches/"
export const COMPANY_CATEOGORY_SETTINGS = "api/user-company-category/"
export const WEBSITE_MONITORING = "api/website-monitoring/"
export const WEBSITE_MONITORING_DATA = "api/website-data/"
export const TWISTED_DNS = "api/twisted-dns/"
export const DATA_LEAK = "api/data-leak/"
export const RECENT_DATA_LEAK = "api/recent-data-leak-search/"
export const SOCIAL_MEDIA = "api/social-media/"
export const CHANGE_PASSWORD = "api/users/change-password/"
export const RESET_PASSWORD = BASE_URL + "password/change/"
export const LOGOUT = "logout"
export const SEND_TAKEDOWN_MAIL = "api/send-theft-email/"
export const GET_SUPERUSER = "api/users/superuser/"
export const SEND_APP_TAKEDOWN_MAIL = "api/send-app-takedown-email/"
export const SEND_DARKWEB_TAKEDOWN_MAIL = "api/dark-web-takedown/"
export const SEND_IMAGE_TAKEDOWN_MAIL = "api/send-google-vision-takedown-email/"
export const SEND_YOUTUBE_TAKEDOWN_MAIL = "/api/send-youtube-takedown-email/"
export const GET_TAKEDOWN_MAIL = "api/fetch-theft-email-info/"
export const UPDATE_TAKEDOWN_MAIL = "api/update-theft-email-info/"
export const UNREADNOTIFICATIONS = "api/fetch-all-unread-notifications/"
export const READNOTIFICATIONS = "api/read-all-notifications/"
export const SOCIAL_MEDIA_PERCENTAGE = "api/social-media-percentage/"
export const ADD_KEYWORDS = "api/add-keyword/"
export const DELETE_KEYWORDS = "api/remove-keyword/"
export const ADD_DOMAINS = "api/add-domain/"
export const SEND_TAKEDOWN = "api/send-theft-email/"
export const FETCH_TAKEDOWN = "api/fetch-theft-email-info/"
export const FETCH_TAKEDOWN_CHART = "api/takedown-info-bar-chart/"
export const FETCH_CATEGORY_TAKEDOWN_CHART = "api/analysis_takedown_bar_chart/"
export const UPDATE_TAKEDOWN = "api/update-theft-email-info/"
export const GET_MONITORED_KEYWORDS = "api/monitored-keywords/"
export const GET_SUGGESTED_KEYWORDS = "/api/suggested-keywords/"
export const GET_PDF = "api/pdf-report/"
export const GET_LATEST_KEYWORD_SEARCH = "api/latest-keyword-search/"
export const GET_COMPANY_CATEGORY = "api/get-company-category/"
export const SEND_OTP = "api/sent-otp/"
export const VERIFY_OTP = "api/verify-otp/"
export const CHANGE_FORGOT_PASSWORD = "api/forgot-password/"
export const GET_GOOGLE_NEWS = "api/google-company-link/"
export const GET_NEWS = "api/google-news/"
export const GET_COMPANY_DETAILS = "api/get-userdomain-company_name/"
export const GET_PULSE_DATA = "api/get-pulse-data/"
export const GET_BBOT = "api/bbot-records/"
export const GET_DARKWEB_DATA = "api/dark-web-data"
export const SEARCH_DARKWEB_DATA = "api/dark-web/"
export const DELETE_NEWS = "api/remove-google-company-link/"
export const GET_SSL_STATUS = "api/check-ssl/"
export const GET_WHO_IS = "api/twisted-dns-whois-data/"
export const GET_WEBSITE_DATA = "api/website-data/"
export const DELETE_NOTIFICATION = "api/delete_notification/"
export const SEND_DATA_LEAK_TAKEDOWN_MAIL = "api/data-leak-takedown-email/"
export const SEND_JOB_TAKEDOWN_MAIL = "api/send-job-takedown-email/"
export const FILTER_THEFT_EMAIL = "api/navigation-filter-theft-email/"
export const GET_ALL_WEBMONITORING_DATA = "api/fetch-website-monitoring/"
export const GET_DASHBOARD_STATS = "api/dashboard_count_take_down/"
export const GET_PRIORITY_GRAPH = "api/graph-takedown-priority/"
export const GET_SOURCE_DNS = "api/get-source-dns"
export const FETCH_NAVIGATION_TAKEDOWN = "api/navigation-filter-theft-email/"
export const GET_ALL_WEBMONITORING_PARAMS = "api/twisted-dns-parameter-list/"
export const GET_WEBMONITORING_DASHBOARD = "api/dashboard/website-monitoring/"
export const GET_TRENDS_DASHBOARD = "api/dashboard/trends/"
export const CHANGE_USER_DETAILS = "api/users/"
export const GET_USER = "api/users/"
export const SEND_PDF = "api/email-pdf-report/"
export const GET_APP = "api/mobile_app_search/"
export const GET_SOCIAL_ACC = "api/users/social-media-handles/"
export const DELETE_APP = (id = "") => `/api/remove_company_app/${id}`
export const DELETE_IMAGE = (id = "") => `/api/remove-google-vision-data/${id}`
export const UPDATE_SOCIAL_ACC = (id = "") =>
  `/api/users/social-media-handles/${id}/`
export const DELETE_SUGGESTED_KEYWORD = (id = "") =>
  `api/remove-suggested-keyword/${id}`
export const DELETE_YOUTUBE = (id = "") => `api/remove-youtube-search/${id}`
export const ADD_COMPETITOR = "api/add-competitor-website/"
export const YOUTUBE = "api/youtube-search/"
export const DELETE_WEBSITE = "api/remove-website-monitoring/"
export const REMOVE_JOB_SEARCH = "api/job-remove/"
export const TWISTED_PDF = "api/twisted-dns-pdf/"
export const WEBSITE_PDF = "api/web-monitoring-pdf/"
export const RAISED_PDF = "api/raised-event-pdf/"
export const DARKWEB_PDF = "api/dark-web-pdf/"
export const TWISTED_PDF_MAIL = "api/twisted-dns-pdf-to-mail/"
export const GOOGLE_VISION = "/api/website-monitor-google-vision"
export const GOOGLE_COMPANY_REVIEW = "api/company-google-review/"
export const GOOGLE_ID = "api/auto-complete-google-place-id/"
export const UPDATE_GOOGLE_ID = "api/company-location-id-update/"

export const CREATE_TEAM = "/api/users/teams/"
export const GOOGLE_REVIEW = "api.reviewsmaker.com/gmb/"
export const UPDATE_TEAM = (id = "") => `api/users/teams/${id}/`
export const DELETE_TEAM = (id = "") => `api/users/teams/${id}/`
export const GET_INVITED_LIST = "api/users/invitations/"
export const CANCEL_INVITATION = "api/users/invitations"
export const TWITTER_TIMELINE = "api/social/twitter/timelines/"
export const MONITOR_USER = "api/social/twitter/timeline-monitor/"
export const SEND_INVITE = "api/users/send-invitation/"
export const INVITE_LOGIN = "api/users/invitation/accept/"
export const DELETE_TEAM_MEMBER = "api/users/remove-team-member"
export const SYSTEM_HEALTH = "api/core/system-health/"
export const SEARCH_SOCIAL_MEDIA = "api/social/twitter/search"
export const NEW_SEARCH_SOCIAL_MEDIA =
  "https://website-contacts-scraper.p.rapidapi.com/scrape-contacts"
export const ADMIN_LIST = "api/users/superuser/admin-users/"
export const UPDATE_ADMIN_MONITOR = "api/users/superuser/"
