let BASE_URL = "http://150.230.48.46:8888"
if (process.env.NODE_ENV !== "production") {
  BASE_URL = "http://150.230.48.46:8888"
}

export const LOGIN = BASE_URL + "api/users/login/"
export const REGISTER = BASE_URL + "register/"
export const SIGNUP = BASE_URL + "signupone/"
export const SIGNUPTWO = BASE_URL + "signuptwo/"
export const SIGNUPTHREE = BASE_URL + "signupthree/"
export const DASHBOARD = BASE_URL + "api/dashboard/"
export const COMPANY_CATEOGORY_SETTINGS = "api/user-company-category/"
export const WEBSITE_MONITORING = BASE_URL + "api/website-monitoring/"
export const WEBSITE_MONITORING_DATA = BASE_URL + "api/website-data/"
export const TWISTED_DNS = BASE_URL + "api/twisted-dns/"
export const DATA_LEAK = BASE_URL + "api/data-leak/"
export const RECENT_DATA_LEAK = BASE_URL + "api/recent-data-leak-search/"
export const SOCIAL_MEDIA = BASE_URL + "api/social-media/"
export const CHANGE_PASSWORD = BASE_URL + "api/users/"
export const LOGOUT = BASE_URL + "logout"
export const SEND_TAKEDOWN_MAIL = BASE_URL + "api/send-theft-email/"
export const GET_TAKEDOWN_MAIL = BASE_URL + "api/fetch-theft-email-info/"
export const UPDATE_TAKEDOWN_MAIL = BASE_URL + "api/update-theft-email-info/"
export const UNREADNOTIFICATIONS =
  BASE_URL + "api/fetch-all-unread-notifications/"
export const READNOTIFICATIONS = BASE_URL + "api/read-all-notifications/"
export const SOCIAL_MEDIA_PERCENTAGE = BASE_URL + "api/social-media-percentage/"
export const ADD_KEYWORDS = BASE_URL + "api/add-keyword/"
export const ADD_DOMAINS = BASE_URL + "api/add-domain/"
export const SEND_TAKEDOWN = BASE_URL + "api/send-theft-email/"
export const SEND_APP_TAKEDOWN = BASE_URL + "api/send-app-takedown-email/"
export const FETCH_TAKEDOWN = BASE_URL + "api/fetch-theft-email-info/"
export const FETCH_TAKEDOWN_CHART = BASE_URL + "api/takedown-info-bar-chart/"
export const UPDATE_TAKEDOWN = BASE_URL + "api/update-theft-email-info/"
export const GET_MONITORED_KEYWORDS = BASE_URL + "api/monitored-keywords/"
export const GET_PDF = "api/pdf-report/"
export const SEND_PDF = "api/email-pdf-report/"
export const GET_LATEST_KEYWORD_SEARCH = BASE_URL + "api/latest-keyword-search/"
export const GET_COMPANY_CATEGORY = BASE_URL + "api/get-company-category/"
export const SEND_OTP = BASE_URL + "api/sent-otp/"
export const VERIFY_OTP = BASE_URL + "api/verify-otp/"
export const CHANGE_FORGOT_PASSWORD = BASE_URL + "api/forgot-password/"
export const FETCH_TOP_GOOGLE_SEARCH = BASE_URL + "api/google-company-link/"
export const DELETE_TOP_GOOGLE_SEARCH =
  BASE_URL + "api/remove-google-company-link/"
export const FETCH_NOTIFICATIONS_SETTINGS =
  BASE_URL + "api/notification-settings/"
export const GET_APP = "/api/mobile_app_search/"
export const ADD_COMPETITOR = "api/add-competitor-website/"
export const TWISTED_PDF = "api/twisted-dns-pdf/"
export const WEBSITE_PDF = "api/web-monitoring-pdf/"
export const RAISED_PDF = "api/raised-event-pdf/"
export const DARKWEB_PDF = "api/dark-web-pdf/"
export const TWISTED_PDF_MAIL = "api/twisted-dns-pdf-to-mail/"
