export const API_INVOCATION = "API_INVOCATION"
export const SHOW_TOAST_MESSAGE = "SHOW_TOAST_MESSAGE"
export const RESET_SHOW_TOAST_MESSAGE = "RESET_SHOW_TOAST_MESSAGE"
export const START_LOADER = "START_LOADER"
export const STOP_LOADER = "STOP_LOADER"

// Login actions
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

//register actions
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

//register step 2 actions
export const REGISTER_USER_STEP2 = "REGISTER_USER_STEP2"
export const REGISTER_USER_STEP2_SUCCESS = "REGISTER_USER_STEP2_SUCCESS"
export const REGISTER_USER_STEP2_ERROR = "REGISTER_USER_STEP2_ERROR"

//register step 3 actions
export const REGISTER_USER_STEP3 = "REGISTER_USER_STEP3"
export const REGISTER_USER_STEP3_SUCCESS = "REGISTER_USER_STEP3_SUCCESS"
export const REGISTER_USER_STEP3_ERROR = "REGISTER_USER_STEP3_ERROR"

//dashboard
export const DASHBOARD = "DASHBOARD"
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS"
export const DASHBOARD_ERROR = "DASHBOARD_ERROR"

//websiteMonitoring
export const WEBSITE_MONITORING = "WEBSITE_MONITORING"
export const WEBSITE_MONITORING_SUCCESS = "WEBSITE_MONITORING_SUCCESS"
export const WEBSITE_MONITORING_ERROR = "WEBSITE_MONITORING_ERROR"

//twisted DNS
export const TWISTED_DNS = "TWISTED_DNS"
export const TWISTED_DNS_SUCCESS = "TWISTED_DNS_SUCCESS"
export const TWISTED_DNS_ERROR = "TWISTED_DNS_ERROR"

//twisted DNS
export const DATA_LEAK = "DATA_LEAK"
export const DATA_LEAK_SUCCESS = "DATA_LEAK_SUCCESS"
export const DATA_LEAK_ERROR = "DATA_LEAK_ERROR"

//social media
export const SOCIAL_MEDIA = "SOCIAL_MEDIA"
export const SOCIAL_MEDIA_SUCCESS = "SOCIAL_MEDIA_SUCCESS"
export const SOCIAL_MEDIA_ERROR = "SOCIAL_MEDIA_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR"

export const USER_PROFILE = "USER_PROFILE"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR"
